### ISSUE TITLE
New stuff

### ISSUE THREAD

**Issue by Stanzilla** [BigWigsMods/BigWigs_CommonAuras#1]
- Raid Utility Item
  - [x] http://www.wowhead.com/spell=226234/codex-of-the-tranquil-mind
- Single CDs
  - [x] http://www.wowhead.com/spell=204018/blessing-of-spellwarding
- Raid Utility CDs
  - [x] http://www.wowhead.com/spell=192077/wind-rush-totem
- Raid Defensive CDs
  - [x] http://www.wowhead.com/spell=204150/aegis-of-light
- Demon Hunter Single CD
  - [x] http://www.wowhead.com/spell=191427/metamorphosis
  - [x] http://www.wowhead.com/spell=207810/nether-bond
- Demon Hunter Raid Defensive CDs:
  - [x] http://www.wowhead.com/spell=196718/darkness

**Comment by nebularg** [comment]
Gonna hold onto codex handling for now since I needed to add UNIT_SPELLCAST event watching to deal with it. Hopefully they fix it.
