### ISSUE TITLE
Horrible lag when i have this addon enabled

### ISSUE THREAD

**Issue by RainbowTea** [BigWigsMods/BigWigs_CommonAuras#14]
i installed this addon last night, only used it on 1 boss and noticed horrible lag, it occured to me to disable the last thing i installed, which was this. (herpic rastakhan) 

after i disabled it , my lag was gone. i went from 30 fps or even less to back to my normal 130 fps +

I'm not sure what kind of information i can provide besides the version i installed
 v8.1.1

please let me know how i can help or what i can do! :)

**Comment by nebularg** [comment]
Sorry, I've never experienced that. Are you sure you didn't get any other errors during that time? Do you have BugGrabber/BugSack installed?

**Comment by funkydude** [comment]
Also the addon doesn't warn for anything by default. So whatever ability you've enabled warnings for, try disabling it and seeing if the issue is resolved.

**Comment by RainbowTea** [comment]
Bigwigs by default does not, its the commonauras addon to it that does.

**Comment by RainbowTea** [comment]
I believe i  do not..but i'll get something for it and get the errors if
possible.

**Comment by funkydude** [comment]
> Bigwigs by default does not, its the commonauras addon to it that does.

What? BWCA doesn't warn for *anything* by default.
Like I already stated. Whatever abilities you've enabled in BWCA, disable them and see if the issues persists.
Also, list them here.

**Comment by RainbowTea** [comment]
Okay, i think we are getting the  wording incorrect here or you read the wrong post and replied to the wrong post. (which im realizing now i have no idea what you're going on about)

You were the only one that mentioned it warnings.
Which i -never- did mention any warnings untill you commented, i only mentioned that when i have it installed, it causes lag.

However, When i said  warnings to your REPLY, i mean **' Displays messages and bars for common raid cooldowns.'** (this is taken DIRECTLY, from the addon ITSELF).

I'm going to get more information the next time i am available to gather it and record it and get errors if possible.I have only used the defaults in the addon itself.

**Comment by nebularg** [comment]
The CommonaAuras default is to do nothing 😛 you need to go into the config and enable the spells you want to show. He was asking what you had enabled so we could look for a specific cause.

**Comment by funkydude** [comment]
No response, closing.
