### ISSUE TITLE
LUA Error with Portal to Valdrakken portal

### ISSUE THREAD

**Issue by Fraktyl** [BigWigsMods/BigWigs_CommonAuras#15]
Whenever a mage casts the Valdrakken portal it throws a LUA error:

Version: 10.0.2

`7x BigWigs_CommonAuras/CommonAuras.lua:844: attempt to call field '?' (a nil value)
[string "@BigWigs_CommonAuras/CommonAuras.lua"]:844: in function <BigWigs_CommonAuras/CommonAuras.lua:838>

Locals:
_ = 1671335900.503000
event = "SPELL_CREATE"
_ = false
_ = "Player-3678-07B67DF3"
source = "Konstantinov"
_ = 1300
_ = 0
_ = "GameObject-0-4218-2522-8185-384641-00001E8FDC"
target = "Portal to Valdrakken"
_ = 16936
_ = 0
spellId = 395289
spellName = "Portal: Valdrakken"
f = "Portal"
(*temporary) = nil
(*temporary) = <table> {
 Revival = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1103
 BlessingOfProtection = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1128
 FortifyingBrew = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1084
 CheckOption = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:110
 BlessingOfSacrificeOff = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1138
 FieryBrand = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:971
 enabled = true
 SymbolOfHope = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1200
 GetLocale = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:17
 TranquilityOff = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1032
 PLAYER_REGEN_DISABLED = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:819
 GuardianSpiritOff = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1178
 DivineHymnOff = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1169
 Custom = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:858
 AutoHammer = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:893
 AbominationLimb = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:916
 Blur = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:961
 RegisterMessage = <function> defined @BigWigs/Loader.lua:1041
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:1062
 AuraMastery = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1123
 Darkness = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:966
 db = <table> {
 }
 Lightwell = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1186
 LastStand = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1271
 NetherwalkOff = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:986
 SPELL_DATA_LOAD_RESULT = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:122
 PowerWordBarrier = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1195
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 Barkskin = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:992
 ZenMeditation = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1107
 OnPluginEnable = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:735
 DiffuseMagic = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1079
 ShieldWall = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1281
 GuardianSpirit = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1173
 RenewingBlaze = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1043
 ObsidianScales = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1038
 DancingRuneWeapon = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:931
 GuardianOfAncientKings = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1157
 subPanelOptions = <table> {
 }
 Soulwell = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1256
 OnPluginDisable = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:746
 SummoningStone = <function> defined @BigWigs_CommonAuras/CommonAuras.lua:1260
 DivineShield = <function> defined @Big`

**Comment by nebularg** [comment]
Thanks, I fixed that then forgot about it 😓
