### ISSUE TITLE
Localization contribution: more information about context is needed

### ISSUE THREAD

**Issue by exarus** [BigWigsMods/BigWigs_CommonAuras#5]
I'm going to contribute the Russian translation for BigWigs.
But I didn't got the context of "L.self", "L.group".
Is the "Group", "Self" "Healer" are meant to be adjectives?
The idea behind these words, is to describe the type of aura, isn't it? If so, then I don't understand why adjective is not used in German translation. And I'm definetely have to switch to adjectives in Russian.

**Comment by funkydude** [comment]
We leave it up to the translator to decide in what way they should translate a word and (at least we hope) that context it enough to carry that through. The context of these words in this addon (being an aura tracking addon) is "auras a player can cast on themselves", "auras a player can cast on their group", "auras only healers care about", etc.

**Comment by exarus** [comment]
Thanks a lot. I'm going to close this. You might want to label this as question BTW.
